const { app } = require("./Server");
const User = require("../routes/User");
const Admin = require("../routes/Admin");
const Brand = require("../routes/Brand");
const Category = require("../routes/Category");
const Product = require("../routes/Product");
const Address = require("../routes/Address");
const Bank = require("../routes/Bank");
const Discount = require("../routes/Discount");
const Sale = require("../routes/Sale");
const Coupon = require("../routes/Coupon");
const Wishlist = require("../routes/Wishlist");
const Blog = require("../routes/Blog");
const Review = require("../routes/Review");
const { GetImage } = require("../routes/Image");

app.use(User);
app.use(Sale);
app.use(Coupon);
app.use(Discount);
app.use(Bank);
app.use(Address);
app.use(Product);
app.use(Category);
app.use(Brand);
app.use(Admin);
app.use(Wishlist);
app.use(Blog);
app.use(Review);
app.use(GetImage);
