version: 2
updates:
  - package-ecosystem: npm
    directory: /Backend
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /Frontend
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /admin
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
